# Generated by Django 3.2.6 on 2021-09-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='default',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='blank', upload_to='product/'),
            preserve_default=False,
        ),
    ]
