# Generated by Django 3.2.6 on 2021-09-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210913_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='商品名稱',
        ),
    ]
